version: '2.1'

services:
  api:
    build: .
    environment:
      PGUSER: postgres
      PGPASSWORD: test
      PGDATABASE: test
      PGHOST: db
      PGPORT: 5432
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      ALLOW_IP_RANGE: 0.0.0.0/0
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
